// RandomTextView.swift

import SwiftUI

class RandomTextViewModel: ObservableObject {
    @Published var currentText: String = ""
    
    private let textOptions: [String] = [
        "Breathe in peace, exhale stress.",
        "Stillness leads to inner peace.",
        "Live and feel this moment.",
        "Mindfulness is freedom's path.",
        "Release past, embrace now.",
        "Accept what is, let go.",
        "Calmness is your superpower.",
        "Every breath rebalances you.",
        "Silence carries answers.",
        "Peace begins within.",
        "Embrace life in stillness.",
        "Seek balance, not perfection.",
        "Emotions are fleeting visitors.",
        "Inhale future, exhale past.",
        "Peace amid the storm.",
        "Let worries flow away.",
        "Mindful living is a journey.",
        "Bring your own sunshine.",
        "Be still, listen to world.",
        "Silence speaks volumes.",
        "Inner peace is self-control.",
        "Simplicity is sophistication.",
        "Find peace in yourself.",
        "Quieter minds hear more.",
        "Peace is accepting life.",
        "Adjust your sails.",
        "Find peace within.",
        "Let go of weak thoughts.",
        "Trust life's timing.",
        "Gratitude is enough.",
        "Inhale courage, exhale fear.",
        "Smile, breathe, go slowly.",
        "Happiness is a choice.",
        "Be here now.",
        "Silence is strength.",
        "You are the ocean.",
        "Realize your inner power.",
        "Present moment is all.",
        "Mind shapes your being.",
        "Breathe, anchor yourself.",
        "Return to present with breath.",
        "Relaxed body, inner peace.",
        "Silence the mind, heal soul.",
        "Don't dwell on yesterday.",
        "Calm mind, ultimate weapon.",
        "Meditation isn't controlling thoughts.",
        "Nourish yourself with silence.",
        "Embrace tranquility within.",
        "Harmony resides within you.",
        "Nature mirrors calmness.",
        "Just be present.",
        "Find joy in simplicity.",
        "You are enough.",
        "Embrace the journey.",
        "Calm is a super power.",
        "Breathe, you're alive.",
        "Flow with life.",
        "Your peace, your power.",
        "Witness life unfolding.",
        "Inhale peace, exhale chaos.",
        "Find beauty in stillness.",
        "Serenity in each breath.",
        "Be water, my friend.",
        "Dwell in possibility.",
        "Awaken to the moment.",
        "Soften into this moment.",
        "Rest in awareness.",
        "Let go, and grow.",
        "Exhale doubt, inhale courage.",
        "Feel, don't think.",
        "Your path is sacred.",
        "Patience fosters growth.",
        "Life flows like a river.",
        "Savor each moment.",
        "Calm amidst the chaos.",
        "Acceptance is freedom.",
        "Gratitude fuels happiness.",
        "Seek wisdom in silence.",
        "Peaceful heart, peaceful life.",
        "Balance is key.",
        "Your journey, your pace.",
        "Breathe out, release.",
        "Believe in your strength.",
        "Trust your inner wisdom.",
        "Compassion starts within.",
        "Live in gratitude.",
        "Inner peace, outer strength.",
        "Gentle is powerful.",
        "Be present, be free.",
        "Focus on now.",
        "Breathe in, let go.",
        "Calm mind, calm life.",
        "Feel life's rhythm.",
        "Surrender to serenity.",
        "One breath at a time.",
        "Listen to your heart.",
        "Relax and breathe, find peace.",
        "Mindfulness brings inner tranquility.",
        "Take a deep breath, release tension.",
        "Silence the mind, embrace serenity.",
        "Breathe in calm, exhale stress.",
        "Meditate to quiet the mind.",
        "Inhale clarity, exhale distractions.",
        "Find stillness in the present moment.",
        "Focus on your breath, find balance.",
        "Let go of worries with each exhale.",
        "Create space for calmness within.",
        "Connect with your breath, find peace.",
        "Breathe deeply, let go of anxiety.",
        "Meditation calms the racing thoughts.",
        "Inhale positivity, exhale negativity.",
        "Embrace the power of deep breaths.",
        "Find solace in the rhythm of breathing.",
        "Quiet the mind, awaken inner stillness.",
        "Breathe in energy, exhale fatigue.",
        "Let your breath anchor your presence.",
        "Calm your mind through steady breaths.",
        "Meditation opens the door to serenity.",
        "Inhale peace, exhale restlessness.",
        "Find refuge in the breath's gentle flow.",
        "Release tension with every exhale.",
        "Breathe deeply, invite tranquility.",
        "Meditate to find inner harmony.",
        "Inhale calmness, exhale agitation.",
        "Connect with your breath, find peace.",
        "Release stress with each conscious breath.",
        "Breathe in calmness, exhale anxiety.",
        "Meditation soothes the restless soul.",
        "Inhale serenity, exhale worries.",
        "Find solace in mindful exhales.",
        "Center yourself through rhythmic breathing.",
        "Inner peace resides in mindful stillness.",
        "Harness the power of focused breath.",
        "Embrace the calmness within you.",
        "Meditation is a gateway to serenity.",
        "Inhale peace, exhale chaos.",
        "Be present in the soothing breaths.",
        "Find harmony through mindful inhalation.",
        "Calmness lies within each deep breath.",
        "Meditate to restore balance within.",
        "Breathe deeply, find your calm.",
        "Still your mind, unlock tranquility.",
        "Let each breath guide you home.",
        "Breathe in, let stress out.",
        "Meditation soothes the restless soul.",
        "Inhale tranquility, exhale worries.",
        "Peaceful silence whispers inner calm.",
        "Breathe in, let stress out.",
        "Meditation soothes the restless soul.",
        "Find solace in mindful exhales.",
        "Center yourself through rhythmic breathing.",
        "Inner peace resides in mindful stillness.",
        "Harness the power of focused breath.",
        "Embrace the calmness within you.",
        "Meditation is a gateway to serenity.",
        "Inhale peace, exhale chaos.",
        "Be present in the soothing breaths.",
        "Find harmony through mindful inhalation.",
        "Calmness lies within each deep breath.",
        "Meditate to restore balance within.",
        "Breathe deeply, find your calm.",
        "Still your mind, unlock tranquility.",
        "Let each breath guide you home.",
        "Breathe in, let stress out.",
        "Meditation soothes the restless soul.",
        "Inhale tranquility, exhale worries.",
        "Peaceful silence whispers inner calm.",
        "Breathe in, let stress out.",
        "Meditation soothes the restless soul.",
        "Find solace in mindful exhales.",
        "Center yourself through rhythmic breathing.",
        "Inner peace resides in mindful stillness.",
        "Harness the power of focused breath.",
        "Embrace the calmness within you.",
        "Meditation is a gateway to serenity.",
        "Inhale peace, exhale chaos.",
        "Be present in the soothing breaths.",
        "Find harmony through mindful inhalation.",
        "Calmness lies within each deep breath.",
        "Meditate to restore balance within.",
        "Breathe deeply, find your calm.",
        "Still your mind, unlock tranquility.",
        "Let each breath guide you home.",
        "Breathe in, let stress out.",
        "Meditation soothes the restless soul.",
        "Inhale tranquility, exhale worries.",
        "Peaceful silence whispers inner calm.",
        "Breathe in, let stress out.",
        "Meditation soothes the restless soul.",
        "Find solace in mindful exhales.",
        "Center yourself through rhythmic breathing.",
        "Inner peace resides in mindful stillness.",
        "Harness the power of focused breath.",
        "Embrace the calmness within you.",
        "Meditation is a gateway to serenity.",
        "Inhale peace, exhale chaos.",
        "Be present in the soothing breaths.",
        "Find harmony through mindful inhalation.",
        "Calmness lies within each deep breath.",
        "Meditate to restore balance within.",
        "Breathe deeply, find your calm.",
        "Pause and reconnect within.",
        "Inhale love, exhale fear.",
        "Let gratitude fill your heart.",
        "Every moment is a gift.",
        "Discover peace in simplicity.",
        "Stillness is the gateway to insight.",
        "Peaceful mind, joyful heart.",
        "Breathe out negativity, breathe in positivity.",
        "Meditation is self-discovery.",
        "Find solace in nature's embrace.",
        "Calmness anchors you to the present.",
        "Be kind to yourself always.",
        "The present moment is all there is.",
        "Stillness is the language of the soul.",
        "Embrace change with an open heart.",
        "Quiet the mind, hear your soul.",
        "Find beauty in the present chaos.",
        "Compassion heals both giver and receiver.",
        "Let go of judgment, embrace acceptance.",
        "Serenity shines from within.",
        "Breathe deeply, find your center.",
        "The journey within is infinite.",
        "Happiness lies in small moments.",
        "Embrace uncertainty with courage.",
        "Calmness nurtures creativity.",
        "Your breath is your anchor.",
        "Meditation is a path to wholeness.",
        "Inhale possibilities, exhale limitations.",
        "Connect with the energy of life.",
        "Peace begins with a smile.",
        "Trust the process of life.",
        "Stillness is the rhythm of the universe.",
        "Embrace the power of now.",
        "Let your breath guide your thoughts.",
        "Acceptance is the key to serenity.",
        "Breathe in energy, breathe out doubt.",
        "Meditation is food for the soul.",
        "Inner peace blooms like a flower.",
        "Release attachments, find freedom.",
        "Calmness is a state of grace.",
        "Inhale presence, exhale distractions.",
        "Let love and compassion be your compass.",
        "Quiet your mind, hear your intuition.",
        "Simplicity is the essence of life.",
        "Breathe deeply, invite peace.",
        "The universe is within you.",
        "Meditation is a sanctuary for the mind.",
        "Inhale courage, exhale doubt.",
        "Peace is found in the present.",
        "Find your sanctuary in stillness.",
        "Embrace impermanence with grace.",
        "Let go of the need to control.",
        "Calmness is the dance of the soul.",
        "Breathe in joy, breathe out gratitude.",
        "Meditation is a journey inward.",
        "Inhale strength, exhale weakness.",
        "Find wisdom in the silence.",
        "Trust in the unfolding of life.",
        "Embrace the beauty of the unknown.",
        "Breathe deeply, release tension.",
        "Meditation is the art of letting go.",
        "Inhale balance, exhale chaos.",
        "Peace resides in your heart.",
        "Let your breath carry you home.",
        "Discover peace through self-awareness.",
        "Calmness is the song of the soul.",
        "Breathe in stillness, exhale restlessness.",
        "Meditation opens the door to serenity.",
        "Inhale clarity, exhale confusion.",
        "Surrender to the flow of life.",
        "Embrace each moment as it is.",
        "Breathe deeply, find your peace.",
        "Meditation is a meeting with yourself.",
        "Inhale compassion, exhale judgment.",
        "Seek stillness amidst the noise.",
        "Quiet the mind, find your truth.",
        "Embrace the silence between thoughts.",
        "Breathe in patience, breathe out tension.",
        "Meditation is the language of the soul.",
        "Inhale acceptance, exhale resistance.",
        "Find harmony in the present moment.",
        "Release the past, embrace the now.",
        "Calmness is the dance of life.",
        "Breathe in the beauty of existence.",
        "Meditation is a journey of self-discovery.",
        "Inhale gratitude, exhale complaints.",
        "Let go of the need to be busy.",
        "Embrace the stillness of the night.",
        "Breathe deeply, find your center.",
        "Meditation is the key to inner peace.",
        "Inhale hope, exhale despair.",
        "Discover yourself in the present.",
        "Trust in the wisdom of life.",
        "Embrace the power of silence.",
        "Breathe in the light, exhale darkness.",
        "Meditation is the art of being.",
        "Inhale forgiveness, exhale resentment.",
        "Find peace in the present chaos.",
        "Let your breath be your guide.",
        "Calmness is the gateway to bliss.",
        "Breathe in awareness, breathe out distraction.",
        "Meditation is the path to freedom.",
        "Inhale strength, exhale fear.",
        "Embrace the silence within.",
        "Breathe deeply, find your peace.",
        "Embrace the calm, release the chaos.",
        "Your breath, your anchor.",
        "Inhale serenity, exhale anxiety.",
        "Peace blooms within.",
        "Your journey, your pace.",
        "Inhale love, exhale fear.",
        "Trust the journey.",
        "Stillness is a treasure.",
        "Breathe deeply, live fully.",
        "Mindfulness, the path to freedom.",
        "Simplicity breeds contentment.",
        "Seek stillness, find clarity.",
        "Embrace the now, find peace.",
        "Breathe in, hold, release.",
        "Silence is a source of strength.",
        "Inhale wisdom, exhale ignorance.",
        "Life is a flow, go with it.",
        "Mindfulness is the light of awareness.",
        "Breathe in life, exhale gratitude.",
        "Find grace in the quiet.",
        "Inhale possibility, exhale doubt.",
        "Peace is in every breath.",
        "Stillness, the doorway to peace.",
        "Breathe in confidence, exhale hesitation.",
        "Discover tranquility within chaos.",
        "Inhale love, exhale hatred.",
        "Life is here, in this moment.",
        "Stillness speaks the truth.",
        "Breathe in joy, exhale sorrow.",
        "Find peace in surrender.",
        "Inhale light, exhale darkness.",
        "Savor the sweet simplicity.",
        "Silence, the music of peace.",
        "Breathe in clarity, exhale doubt.",
        "Be present, be peaceful.",
        "Inhale calm, exhale rush.",
        "The moment is now, embrace it.",
        "Silence, the soil of self-discovery.",
        "Breathe in space, exhale clutter.",
        "Be still, discover yourself.",
        "Inhale compassion, exhale judgment.",
        "Life is a flow of love.",
        "Silence, the canvas of creation.",
        "Breathe in courage, exhale fear.",
        "Be present, be patient.",
        "Inhale serenity, exhale stress.",
        "Life unfolds in the present.",
        "Silence, a journey inward.",
        "Breathe in purity, exhale toxicity.",
        "Be here, be clear.",
        "Inhale tranquility, exhale turbulence.",
        "Life is a dance, move gracefully.",
        "Silence, the mirror of the self.",
        "Breathe in vitality, exhale lethargy.",
        "Be present, be precious.",
        "Inhale patience, exhale urgency.",
        "Life is a melody, sing along.",
        "Silence, the realm of realization.",
        "Breathe in faith, exhale doubt.",
        "Be now, be here.",
        "Inhale joy, exhale sadness.",
        "Life is a journey, travel mindfully.",
        "Silence, the seed of serenity.",
        "Breathe in grace, exhale grudge.",
        "Be quiet, be questing.",
        "Inhale silence, exhale noise.",
        "Life is a play, perform passionately.",
        "Silence, the sanctuary of the soul.",
        "Breathe in light, exhale shadow.",
        "Be peaceful, be profound.",
        "Inhale insight, exhale ignorance.",
        "Life is a book, read it.",
        "Silence, the spring of spirit.",
        "Breathe in faith, exhale fright.",
        "Be still, be strong.",
        "Inhale peace, exhale panic.",
        "Life is a breeze, breathe it.",
        "Silence, the signature of the soul.",
        "Breathe in joy, exhale jealousy.",
        "Be serene, be supreme.",
        "Inhale love, exhale liability.",
        "Life is a dance, dance delicately.",
        "Silence, the stream of spirit.",
        "Breathe in strength, exhale stress.",
        "Be simple, be sincere.",
        "Inhale clarity, exhale confusion.",
        "Life is a drama, act adeptly.",
        "Silence, the seed of solitude.",
        "Breathe in grace, exhale grievance.",
        "Be quiet, be quintessential.",
        "Inhale serenity, exhale strife.",
        "Life is a garden, grow graciously.",
        "Silence, the scent of the soul.",
        "Breathe in courage, exhale concern.",
        "Be peaceful, be perceptive.",
        "Inhale harmony, exhale discord.",
        "Life is a flower, bloom brightly.",
        "Silence, the song of the soul.",
        "Breathe in freedom, exhale fear.",
        "Be silent, be soulful.",
        "Inhale light, exhale lack.",
        "Life is a canvas, color it.",
        "Silence, the sanctuary of serenity.",
        "Breathe in beauty, exhale bitterness.",
        "Be quiet, be questioning.",
        "Inhale hope, exhale despair.",
        "Life is a cycle, cycle smoothly.",
        "Silence, the silence of simplicity.",
        "Breathe in bliss, exhale bitterness.",
        "Be tranquil, be transformative.",
        "Inhale understanding, exhale misunderstanding.",
        "Life is a voyage, voyage valiantly.",
        "Silence, the sap of the soul.",
        "Breathe in hope, exhale hesitance.",
        "Be still, be substantial.",
        "Inhale love, exhale lament.",
        "Life is a voyage, voyage valiantly.",
        "Silence, the song of the silent.",
        "Breathe in vitality, exhale vanity.",
        "Be quiet, be qualitative.",
        "Inhale peace, exhale prejudice.",
        "Life is an adventure, advance avidly.",
        "Silence, the soil of serenity.",
        "Breathe in joy, exhale jitter.",
        "Be serene, be significant.",
        "Inhale love, exhale loathing.",
        "Life is a journey, journey joyfully.",
        "Silence, the scene of the soul.",
        "Breathe in courage, exhale cowardice.",
        "Be peaceful, be perceptive.",
        "Inhale calmness, exhale calamity.",
        "Life is a challenge, challenge cheerfully.",
        "Silence, the sanctuary of the serene.",
        "Breathe in strength, exhale sorrow."
    ]
    
    func pickRandomText() {
        currentText = textOptions.randomElement() ?? "No text available"
    }
}

struct RandomTextView: View {
    @ObservedObject var viewModel: RandomTextViewModel
    
    var body: some View {
        @EnvironmentObject var themeManager: ThemeManager  // Theme Management System
        
        Text(viewModel.currentText)
            .foregroundColor(Color("AccentColor"))
            .font(.system(size: 14))
            .fontWeight(.light)
            .onAppear {
                viewModel.pickRandomText()
            }
            .onTapGesture {
                viewModel.pickRandomText()
            }
    }
}
